
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const AdminAccess = lazy(() => import("./pages/AdminAccess.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const AdminInit = lazy(() => import("./pages/AdminInit.tsx"));
const AdminSettings = lazy(() => import("./pages/AdminSettings.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ClientDashboard = lazy(() => import("./pages/ClientDashboard.tsx"));
const ClientOrders = lazy(() => import("./pages/ClientOrders.tsx"));
const ClientProfile = lazy(() => import("./pages/ClientProfile.tsx"));
const CreateOrder = lazy(() => import("./pages/CreateOrder.tsx"));
const DesignDetail = lazy(() => import("./pages/DesignDetail.tsx"));
const DesignGallery = lazy(() => import("./pages/DesignGallery.tsx"));
const Designs = lazy(() => import("./pages/Designs.tsx"));
const EditOrder = lazy(() => import("./pages/EditOrder.tsx"));
const FirebaseTest = lazy(() => import("./pages/FirebaseTest.tsx"));
const ImageGalleryTest = lazy(() => import("./pages/ImageGalleryTest.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const OrderDetail = lazy(() => import("./pages/OrderDetail.tsx"));
const PaymentCancelled = lazy(() => import("./pages/PaymentCancelled.tsx"));
const PaymentSuccess = lazy(() => import("./pages/PaymentSuccess.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const Subscription = lazy(() => import("./pages/Subscription.tsx"));
const Subscriptions = lazy(() => import("./pages/Subscriptions.tsx"));
const TailorDashboard = lazy(() => import("./pages/TailorDashboard.tsx"));
const TailorDesignCreate = lazy(() => import("./pages/TailorDesignCreate.tsx"));
const TailorDesignEdit = lazy(() => import("./pages/TailorDesignEdit.tsx"));
const TailorDesigns = lazy(() => import("./pages/TailorDesigns.tsx"));
const TailorOrders = lazy(() => import("./pages/TailorOrders.tsx"));
const TailorProfile = lazy(() => import("./pages/TailorProfile.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-access", element: <UserGuard><AdminAccess /></UserGuard>},
	{ path: "/adminaccess", element: <UserGuard><AdminAccess /></UserGuard>},
	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard>},
	{ path: "/admin-init", element: <UserGuard><AdminInit /></UserGuard>},
	{ path: "/admininit", element: <UserGuard><AdminInit /></UserGuard>},
	{ path: "/admin-settings", element: <UserGuard><AdminSettings /></UserGuard>},
	{ path: "/adminsettings", element: <UserGuard><AdminSettings /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/client-dashboard", element: <UserGuard><ClientDashboard /></UserGuard>},
	{ path: "/clientdashboard", element: <UserGuard><ClientDashboard /></UserGuard>},
	{ path: "/client-orders", element: <UserGuard><ClientOrders /></UserGuard>},
	{ path: "/clientorders", element: <UserGuard><ClientOrders /></UserGuard>},
	{ path: "/client-profile", element: <UserGuard><ClientProfile /></UserGuard>},
	{ path: "/clientprofile", element: <UserGuard><ClientProfile /></UserGuard>},
	{ path: "/create-order", element: <UserGuard><CreateOrder /></UserGuard>},
	{ path: "/createorder", element: <UserGuard><CreateOrder /></UserGuard>},
	{ path: "/design-detail", element: <UserGuard><DesignDetail /></UserGuard>},
	{ path: "/designdetail", element: <UserGuard><DesignDetail /></UserGuard>},
	{ path: "/design-gallery", element: <UserGuard><DesignGallery /></UserGuard>},
	{ path: "/designgallery", element: <UserGuard><DesignGallery /></UserGuard>},
	{ path: "/designs", element: <UserGuard><Designs /></UserGuard>},
	{ path: "/edit-order", element: <UserGuard><EditOrder /></UserGuard>},
	{ path: "/editorder", element: <UserGuard><EditOrder /></UserGuard>},
	{ path: "/firebase-test", element: <UserGuard><FirebaseTest /></UserGuard>},
	{ path: "/firebasetest", element: <UserGuard><FirebaseTest /></UserGuard>},
	{ path: "/image-gallery-test", element: <UserGuard><ImageGalleryTest /></UserGuard>},
	{ path: "/imagegallerytest", element: <UserGuard><ImageGalleryTest /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/order-detail", element: <UserGuard><OrderDetail /></UserGuard>},
	{ path: "/orderdetail", element: <UserGuard><OrderDetail /></UserGuard>},
	{ path: "/payment-cancelled", element: <UserGuard><PaymentCancelled /></UserGuard>},
	{ path: "/paymentcancelled", element: <UserGuard><PaymentCancelled /></UserGuard>},
	{ path: "/payment-success", element: <UserGuard><PaymentSuccess /></UserGuard>},
	{ path: "/paymentsuccess", element: <UserGuard><PaymentSuccess /></UserGuard>},
	{ path: "/register", element: <UserGuard><Register /></UserGuard>},
	{ path: "/subscription", element: <UserGuard><Subscription /></UserGuard>},
	{ path: "/subscriptions", element: <UserGuard><Subscriptions /></UserGuard>},
	{ path: "/tailor-dashboard", element: <UserGuard><TailorDashboard /></UserGuard>},
	{ path: "/tailordashboard", element: <UserGuard><TailorDashboard /></UserGuard>},
	{ path: "/tailor-design-create", element: <UserGuard><TailorDesignCreate /></UserGuard>},
	{ path: "/tailordesigncreate", element: <UserGuard><TailorDesignCreate /></UserGuard>},
	{ path: "/tailor-design-edit", element: <UserGuard><TailorDesignEdit /></UserGuard>},
	{ path: "/tailordesignedit", element: <UserGuard><TailorDesignEdit /></UserGuard>},
	{ path: "/tailor-designs", element: <UserGuard><TailorDesigns /></UserGuard>},
	{ path: "/tailordesigns", element: <UserGuard><TailorDesigns /></UserGuard>},
	{ path: "/tailor-orders", element: <UserGuard><TailorOrders /></UserGuard>},
	{ path: "/tailororders", element: <UserGuard><TailorOrders /></UserGuard>},
	{ path: "/tailor-profile", element: <UserGuard><TailorProfile /></UserGuard>},
	{ path: "/tailorprofile", element: <UserGuard><TailorProfile /></UserGuard>},

];
